export { default as Content } from './content'
export { default as Intent } from './intent'
export { default as Main } from './main'
export { default as Size } from './size'
export { default as Variant } from './variant'
